# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose default port (optional for HTTP mode)
EXPOSE 5173

# Start the MCP server over stdio using UV
CMD ["uv", "run", "localdb_app.py"]
